const productos = [{
    id: 1,
    nombre: "Vacunas",
    precio: 1100,
    tamaño: "Único",
    imagenes: "../img/vacunacion.jpg",
},
{
    id: 2,
    nombre: "Chip Identificador",
    precio: 4000,
    tamaño: "Único",
    imagenes: "../img/chipidentificador.jfif",
},
{
    id: 3,
    nombre: "Jaula chica",
    precio: 18000,
    tamaño: "Chico",
    imagenes: "../img/transportadora.jpg",
},
{
    id: 4, 
    nombre: "Jaula mediana",
    precio: 25000,
    tamaño: "Mediano",
    imagenes: "../img/transportadora.jpg",
},
{
    id: 5, 
    nombre: "Jaula grande",
    precio: 32000,
    tamaño: "Grande",
    imagenes: "../img/transportadora.jpg",
},
{
    id: 6,
    nombre: "Canil chico",
    precio: 9000,
    tamaño: "Chico",
    imagenes: "../img/canil.png",
},
{
    id: 7, 
    nombre: "Consulta veterinaria",
    precio: 1300,
    tamaño: "Único",
    imagenes: "../img/consulta.jpg",
},
{
    id: 9,
    nombre: "Bebedero",
    precio: 450,
    tamaño: "Único",
    imagenes: "../img/bebedero.jfif",
},
{
    id: 10,
    nombre: "Comedero",
    precio: 400,
    tamaño: "Único",
    imagenes: "../img/comedero.jpg",
},
]